### ISSUE TITLE
Feature: User can document and rate manga

### ISSUE THREAD

**Issue by jghil** [jghil/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Manga readers will be able to document manga they have read and rate their enjoyment level of the read manga. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive form that allows users to store an image URL with some notes and an enjoyment meter about a manga they've read.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

[User can document and rate manga desktop]
![image](https://user-images.githubusercontent.com/103128961/182435698-252b195d-383c-4b0d-b860-62a8f2f3b081.png)
![image](https://user-images.githubusercontent.com/103128961/182435912-c519f59e-ac67-4e35-b969-e45d9343d59d.png)
[User can document and rate manga mobile]
![image](https://user-images.githubusercontent.com/103128961/182436048-c061ff97-2bfb-4afe-8a14-8791b317a222.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a navbar similar to the ones in the wireframes
    - [x] Within the navbar, create a header called "Manga > Anime".
- [x] Add a ‘div[data-view = “review-form” to HTML
- [x] Add a form for creating a manga review form to the ‘div[data-view=”review-form”]
- [x] Ensure that the form looks nice on both mobile and desktop sized screens
- [x] Make manga title, manga enjoyment meter, date, and best parts, required entries. Photo url will be optional (subject to change).
- [x]  Listen for ‘submit’ events on the manga review form and:
    - [x] Put the form’s input values into a new object.
    - [x] Record the line graph toggles inputs
    - [x] Add the nextEntryId to the object.
    - [x] Increment the nextEntryId on the data model.
    - [x] Prepend the new object to the reviews in the data model.
    - [x] Reset the image preview's `src' attribute.
    - [x] Reset the form inputs.
- [x] Verify the new reviews are saved to local storage along with the rest of the data model on page reload
- [x] Verify each new review receives an incrementing ‘entryId’.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
