### ISSUE TITLE
Feature: User can view manga reviews.

### ISSUE THREAD

**Issue by jghil** [jghil/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Once a user records a manga review, they may want to refer back to it in the future.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Display the user's manga reviews in reverse chronological order so they can see the newest ones first.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

[User can view manga reviews- desktop]
![image](https://user-images.githubusercontent.com/103128961/182438041-622e4e72-ad32-45fc-872b-e5927d1ace7a.png)
[User can view manga reviews- mobile]
![image](https://user-images.githubusercontent.com/103128961/182438255-61a577d4-edac-4890-afe0-8b64b34fd32a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  Add a sibling ‘div[data-view=”reviews”]’ to the HTML.
- [x]  Add an empty unordered list to the ‘div[data-view=”reviews”]’ element in HTML.
- [x]  Add some dummy reviews to ensure the list in HTML matches the wireframes.
- [x] Check that the reviews list looks good on both mobile and desktop screens.
- [x]  Define a function that will take a single review object and returns a DOM tree that matches one of the examples
- [x]  Use a loop to create a DOM tree for each journal entry in the data model and append it to the page when the ‘DOMContentLoaded’ event is fired.
- [x]  Ensure that submitting a new review creates a new DOM tree for it and adds it to the page.
- [x]  Ensure that submitting a new manga review automatically shows the ‘reviews’ view without reloading the page. Use prepend method for this.
- [x]  Remove example HTML reviews once user’s reviews successfully append to the DOM
- [x]  Add a navigation item for reviews to the top right of the page.
- [x]  Add an anchor to Reviews that show review form.
- [x]  Add an anchor to the “Manga > Anime” logo on the top left. This will be a link back to creating a new review.
- [x] Add a "NEW" button on the right of the Your Reviews page. This will be a link back to creating a new review.
- [x]  If there are no reviews ensure that the message appears on the screen.
- [x]  Ensure refreshing pages shows the same view before refreshing.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
