### ISSUE TITLE
Feature: User can make updates.

### ISSUE THREAD

**Issue by jghil** [jghil/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can make updates.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Allow users to select an existing review to edit and pre-populate its information into the form.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

[User can make updates - desktop]
![image](https://user-images.githubusercontent.com/103128961/182439888-e9b55fb8-9fc6-4614-83b2-633154b33c67.png)
[User can make updates - mobile]
![image](https://user-images.githubusercontent.com/103128961/182440017-6691b36c-11eb-4f06-905e-0ab3792f2fea.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update review rendering function to include an edit icon for each rendered review.
- [x] Ensure that each rendered review is given a `data-entry-id` attribute indicating which review it is.
- [x] Listen for clicks on the parent element of all rendered entries.
- [x] Show the entry form if an edit icon was clicked.
- [x] Find the matching review object in the data model and assign it to the data model's `editing` property if an edit icon was clicked.
- [x] Pre-populate the review form with the clicked review's values from the object found in the data model.
- [x] Update the review form's submit handler function to conditionally add a new review object or update the existing one.
- [x] Update the review form's submit handler function to conditionally add a new review DOM tree or replace the existing one.
**Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
