### ISSUE TITLE
Feature: User can search manga 

### ISSUE THREAD

**Issue by jghil** [jghil/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a manga in the search bar.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Allows users to click on the search tag on the top right and search for a manga in the search bar from the Jikan Manga API. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

[User can search manga - desktop]
![image](https://user-images.githubusercontent.com/103128961/182444235-9445f36c-8a7c-4069-8717-dd764c1cd739.png)
[User can search manga - mobile]
![image](https://user-images.githubusercontent.com/103128961/182444373-05cb3281-131c-41ef-9b09-4340cab1718f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling ‘div[data-view=”search-view”]’ in HTML.
- [x] Create a search bar so users will be able to search for specific manga if needed
- [x] Add a sibling ‘div[data-view=”search-results-view”]’ in HTML.
- [x] Add an empty unordered list (‘#manga-results-list') to the ‘div[data-view=”search-results-view”]’ in HTML.
- [x] Query the DOM for the ‘#manga-results-list’ element (Be sure to create it first!)
- [x] Create one manga search result to ensure formatting looks good on both mobile and desktop
- [x] Make a function that:
    - [x] Creates a new XMLHttpReqest Object for manga information (https://api.jikan.moe/v4/manga?q=)
    - [x] Opens the request
    - [x] Sets responseType to JSON
    - [x] Adds a load event listener to obtain: ‘title’, ‘author’, 'chapters', 'genre', 'synopsis', and 'image'
    - [x] Appends the information to the ‘#manga-results-list’ element
- [x] Create a submit event listener for the search manga button that will:
    - [x] Switch views to '#search-results-view'
    - [x] Perform the load event listener mentioned above and display the appended information from the #manga-results-list element
- [x] Add a navigation item for Search to the top right of the page
- [x] Add an anchor to the Search that will show the search page
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by jghil** [comment]
[issue-4-desktop]
![issue-4 desktop](https://user-images.githubusercontent.com/103128961/184264555-ebaaf2b8-44fe-4949-8fca-f92715aa908c.gif)
[issue-4-mobile]
![issue-4 mobile](https://user-images.githubusercontent.com/103128961/184264560-6bbdcfca-9f3c-4b2c-809e-0cdd069a27c2.gif)
