### ISSUE TITLE
Feature: User can receive a random manga to read.

### ISSUE THREAD

**Issue by jghil** [jghil/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can receive a random manga to read.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Allows users to click on the search tag on the top right and then click on the 'Show me a random manga to read' button, which will show them a random manga from the Jikan API in the same format as the manga search results page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

[User can receive a random manga to read - desktop]
![image](https://user-images.githubusercontent.com/103128961/182449731-78abf462-cf2d-443a-a6b7-b02e88e28ec8.png)
[User can receive a random manga to read - mobile]
![image](https://user-images.githubusercontent.com/103128961/182449833-d4e80afa-d80a-4f9c-956b-bdb4341fb288.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In ‘div[data-view=”search-view”]’, create a button that reads: 'Show me a random manga to read!'
- [x] In ‘div[data-view=”search-results-view”]’, make a function that: 
    - [x] Creates a new XMLHttpReqest Object for manga information (https://api.jikan.moe/v4/random/manga)
    - [x] Opens the request
    - [x] Sets responseType to JSON
    - [x] Adds a load event listener to obtain: ‘title’, ‘author’, 'chapters', 'genre', 'synopsis', and 'image'
    - [x] Appends the information to the ‘#manga-results-list’ element
- [x] Create a submit event listener for the random manga button that will:
    - [x] Switch views to '#search-results-view'
    - [x] Perform the load event listener mentioned above and display the appended information from the #manga-results-list element
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
